name: baniadam
description: Demonstrates how to use the flutter_background_geolocation plugin.
version: 1.4.3+14
dependencies:
  flutter:
    sdk: flutter
#  flutter_map:
#    git:
#      # Fork with fix for flutter 1.7
#      url: https://github.com/domesticmouse/flutter_map.git
  unicorndial: ^1.1.4
  flutter_map: ^0.8.2
  shared_preferences: ^0.5.6
  background_fetch: ^0.4.0
  url_launcher: ^5.2.5
  flutter_background_geolocation: ^1.6.1


  cupertino_icons: ^0.1.2
  device_info: ^0.4.1+5
  http: ^0.12.0+2
  grouped_buttons: ^1.0.4
  intl: ^0.16.1
  location: ^2.3.5
  datetime_picker_formfield: ^1.0.0
  image_picker:
  video_player: 0.10.1+5
  camera: ^0.5.4+1
  path_provider: ^1.3.0
  toast: ^0.1.5
#  dio: ^2.1.13
  dio: ^3.0.9
  connectivity: ^0.4.5+2
  access_settings_menu: ^0.0.1
  flutter_exif_rotation: ^0.2.4
  #  cached_network_image: ^1.1.1
  cached_network_image: ^2.0.0
  flutter_launcher_icons: ^0.7.3
  file_picker: ^1.4.3+1
#  google_map_location_picker: ^2.1.0
  google_map_location_picker: ^3.0.0
  google_maps_flutter: ^0.5.21+8
  multiselect_formfield: ^0.1.2
  #  lite_rolling_switch: ^0.1.1
  toggle_switch: ^0.1.4
  custom_switch: ^0.0.1

  # Map markers clustering
  fluster: ^1.1.2

  # Cache manager
  flutter_cache_manager: ^1.1.1
  date_format: ^1.0.8
  firebase_messaging: ^6.0.9
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.3
  firebase_core: ^0.4.4
  random_string: ^2.0.1
#  device_id: ^0.2.0
  flutter_local_notifications: ^0.6.0


dev_dependencies:
  test: ^1.5.1
  flutter_driver:
    sdk: flutter
  colorize: ^2.0.0
#  flutter_background_geolocation:
#    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

flutter_icons:
  android: "launcher_icon"
  iso: true
  image_path: "assets/icons/BaniAdam-Logo-(Mobile-App-Icon).png"


flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 100

  assets:
    - assets/icons/BaniAdam-Logo_Final.png
    - assets/icons/BaniAdam-Logo-(Mobile-App-Icon).png
    - assets/late-today.png
    - assets/on-leave-today.png
    - assets/absent-today.png
    - assets/profile.png
    - assets/arrow6.png
    - assets/arrow14.png
    - assets/arrow25.png
    - assets/arrow_r.png
    - assets/arrow_g.png
    - assets/map_location2.png
    - assets/marker_end.png
    - assets/marker_end1.png
    - assets/marker_end2.png


  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
